### ISSUE TITLE
Issues with yarn install

### ISSUE THREAD

**Issue by eisnerguy1** [cyco/mighty-resource-parser#13]
So, I followed the instructions but, when I get to the **yarn install** part, I get the following output in Terminal:
`yarn install`

**`yarn install v1.22.10`**

`[1/4] 🔍  Resolving packages...`

`[2/4] 🚚  Fetching packages...`

`error @angular-builders/custom-webpack@8.2.0: The engine "node" is incompatible with this module. Expected version ">=10.0.0". Got "9.3.0"`

`error Found incompatible module.`

`info Visit` **`https://yarnpkg.com/en/docs/cli/install`** `for documentation about this command.`

Am I missing something?

**Comment by cyco** [comment]
I think your node version (_9.3.0_) is too old. Can you try updating node to at least 10?

**Comment by eisnerguy1** [comment]
That did it!  It works great.  Is there any way to save the map images like you can with the shapes?

**Comment by cyco** [comment]
You can press `ctrl` and `c` simultaneously to stop the server. I added a button to download map images in 80fc7b0ac7ffdfc4ea1efe3979c3eb2a8b58bf96. Have fun :)
