### ISSUE TITLE
Is there a way to export/download the .image files?

### ISSUE THREAD

**Issue by eisnerguy1** [cyco/mighty-resource-parser#14]
I only had 1 other suggestion/request.   Any chance of adding a download button for the .image files?  I really do appreciate this amazing tool.  It's really cool to see all of the artwork laid out like this.  Thank you!

**Comment by cyco** [comment]
Sure thing, give me a second :)

**Comment by cyco** [comment]
Check out 3c0e8b40d72a0544be1a07e84798a05f3c24043b

**Comment by eisnerguy1** [comment]
<img src="https://media.giphy.com/media/l3V0wkQ2KKcAeW8Cs/giphy.gif">

Seriously, thank you!  I really can't think of anything else to suggest/request.  It's pretty darn perfect now :D
