### ISSUE TITLE
Cannot load content

### ISSUE THREAD

**Issue by ecspresso** [cyco/mighty-resource-parser#16]
I copied the content from https://github.com/jorio/MightyMike (`Data` folder) into `/src/assets` but I only get this when I try to view the files. Any idea?

![20230113_004848 504](https://user-images.githubusercontent.com/17850814/212203230-46bbe37a-4a3a-46e3-860f-79d3ad4f4f73.png)

**Comment by ecspresso** [comment]
My bad. I downloaded the original sit file (https://oldgamesdownload.com/power-pete/) and unpacked it with Stuffit Extender (https://stuffit.com/).

Works as inteded now.

**Comment by cyco** [comment]
Great. I've build this before jorios release and never tried it with the public files.
